spring:
  datasource:
    druid:
      name: druid-database-fireiot #取一个别名供后面quartz调用
      url: jdbc:postgresql://127.0.0.1:5432/test
#      url: ${spring.datasource.url}
      username: postgres
      password: 123456
      driver-class-name: org.postgresql.Driver
      filters: stat
      # 初始连接
      initialSize: 1
      # 最大连接数
      maxActive: 20
      # 获取的最长等待时
      maxWait: 60000
      # 最小空闲连接数
      minIdle: 1
      # 每一分钟执行空闲连接回收
      timeBetweenEvictionRunsMillis: 60000
      # 每十分钟回收空闲连接
      minEvictableIdleTimeMillis: 600000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

  jpa:
      #open-in-view: true
      generate-ddl: true
      hibernate:
        ddl-auto: update
        #use-new-id-generator-mappings: true
      show-sql: true
      properties:
        hibernate:
          enable_lazy_load_no_trans: true
          temp:
            use_jdbc_metadata_defaults: false

  quartz:
      jdbc:
        initialize-schema: never
      job-store-type: jdbc  #默认存储方式为内存方式MEMORY，此处设置为数据方式持久化任务
    properties:
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      org.quartz.jobStore.dataSource: druid-database-fireiot
      org.quartz.threadPool.threadCount: 5
      org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
