spring:
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    name: druid-database-quartz #取一个别名供后面quartz调用
    druid:
      url: jdbc:postgresql://127.0.0.1:5432/test
      username: postgres
      password: 123456
      driver-class-name: org.postgresql.Driver
      filters: stat
      # 初始连接
      initialSize: 1
      # 最大连接数
      maxActive: 20
      # 获取的最长等待时
      maxWait: 60000
      # 最小空闲连接数
      minIdle: 1
      # 每一分钟执行空闲连接回收
      timeBetweenEvictionRunsMillis: 60000
      # 每十分钟回收空闲连接
      minEvictableIdleTimeMillis: 600000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true #打开PSCache,并且指定每个连上PSCach 的大小
      maxOpenPreparedStatements: 20

  jpa:
    #open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      #use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false
  quartz:
    jdbc:
      initialize-schema: never
    job-store-type: jdbc #默认存储方式为内存方式MEMORY，此处设置为数据方式持久化任务
    properties:
      org:
        quartz:
          scheduler:
#            instanceName: quartzTest
            instanceId: AUTO
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
#            dataSource: druid-database-quartz
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
#            tablePrefix: QRTZ_
            clusterCheckinInterval: 20000 #调度实例失效的检查时间间隔
            misfireThreshold: 60000 #容许的最大作业延长时间
            isClustered: false #是否加入集群

          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5 #（threadPriority 属性的最大值是常量 java.lang.Thread.MAX_PRIORITY，等于10。最小值为常量 java.lang.Thread.MIN_PRIORITY，为1）
            threadsInheritContextClassLoaderOfInitializingThread: true


swagger:
  enable: true

  thymeleaf:
    cache: false
